services:
  db:
    image: postgres:15
    container_name: capstone-db-staging
    env_file:
      - .env.staging
    volumes:
      - db_data_staging:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-net

  backend:
    image: rahulsayya/capstone-backend:latest
    container_name: capstone-backend-staging
    env_file:
      - .env.staging
    ports:
      - "8082:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-net

  frontend:
    image: rahulsayya/capstone-frontend:latest
    container_name: capstone-frontend-staging
    ports:
      - "8083:80"
    depends_on:
      - backend
    networks:
      - app-net

volumes:
  db_data_staging:

networks:
  app-net:
    driver: bridge
