services:
  backend:
    build: ./backend
    container_name: backend-prod
    ports:
      - "5002:5000"
    environment:
      ENV: prod
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend-prod
    ports:
      - "8082:80"
    depends_on:
      - backend
    networks:
      - app-net

  db:
    image: postgres:15
    container_name: db-prod
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb_prod
    volumes:
      - db_prod_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  db_prod_data:

networks:
  app-net:
    driver: bridge
