services:
  backend:
    build: ./backend
    container_name: backend-staging
    ports:
      - "5001:5000"
    environment:
      ENV: staging
    depends_on:
      - db
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend-staging
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-net

  db:
    image: postgres:15
    container_name: db-staging
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb_staging
    volumes:
      - db_staging_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  db_staging_data:

networks:
  app-net:
    driver: bridge